### ISSUE TITLE
javax.script 有跟正常controller 做一个性能对比吗

### ISSUE THREAD

**Issue by zwkwd2008** [ssssssss-team/magic-api#15]

**Comment by javamxd** [comment]
没做过对比，跟正常写性能肯定有差距。

**Comment by argan** [comment]
拿测试用例里的performance比了一下，相差还是很大的
`
		MagicScript script = MagicScript.create("var t = System.currentTimeMillis();\n" +
				"var sum = 0L;\n" +
				"for(val in range(0,10000000)){\n" +
				"    sum = sum + val;\n" +
				"}\n" +
				"return sum + \"   \" + (System.currentTimeMillis() - t);", null);
		Object o = MagicScriptEngine.execute(script, new MagicScriptContext());

		System.out.println("run by script " + o);
		long t = System.currentTimeMillis();
		long sum = 0L;
		for (int i = 0; i <= 10000000; i++) {
			sum = sum + i;
		}
		System.out.println("run by java " + sum + "   " + (System.currentTimeMillis() - t));
`

------
`
run by script 50000005000000   464
run by java 50000005000000   12
`

**Comment by argan** [comment]
> 没做过对比，跟正常写性能肯定有差距。

有没有考虑过把script编译成java class来执行？性能一定会好很多

**Comment by javamxd** [comment]
计算的话，效率远不如Java。写一些逻辑，执行SQL，转换一下结果的话，相差不大。
编译成class有研究过。就算实现了，性能是会好点，但也不会好太多的。如果改成强类型的，性能几乎就没啥差别了。

**Comment by wsxe9988** [comment]
Fel表达式引擎,grooy脚本引擎 有没有试过 性能怎么样

**Comment by javamxd** [comment]
`1.5.0`版本之后已经利用`asm`编译成`java class`来执行了，性能有一定的提升。
