### ISSUE TITLE
提供一个通用的文件管理功能

### ISSUE THREAD

**Issue by argan** [ssssssss-team/magic-api#18]
用于管理需要的一些资源文件，例如：服务端渲染的模版文件，配置数据等
并提供相应的文件访问Module

**Comment by javamxd** [comment]
这个好像和这个项目关系就不大了吧，主要是用于提供接口的，这样是走模板引擎渲染了..?

**Comment by argan** [comment]
> 这个好像和这个项目关系就不大了吧，主要是用于提供接口的，这样是走模板引擎渲染了..?

仅提供简单的文件管理功能，至于怎么使用，由开发者自行确定，比如他自己去实现一个freemarker模块，自己实现TemplateLoader 可以访问这些文件就行

**Comment by javamxd** [comment]
这个需求有点太小众了，先观察一段时间看看。
