### ISSUE TITLE
载入xml文件时，会去访问http://ssssssss.org/dtd/0.0.x/ssssssss.dtd。当网络断开时，启动会报错

### ISSUE THREAD

**Issue by ld20052005** [ssssssss-team/magic-api#2]
java.net.UnknownHostException: ssssssss.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_201]

我暂时通过改变在
S8XMLFileParser类里解析xml段的代码避开了解析。但是还是直接读本地dtd最好。我的方式如下：
DocumentBuilder builder=DocumentBuilderFactory.newInstance().newDocumentBuilder();
        	 builder.setEntityResolver(
                     new EntityResolver(){
                        public InputSource resolveEntity(String publicId, String systemId) throws SAXException, IOException
                        {
                            return new InputSource(new StringBufferInputStream(""));  
//                            return null;//这个的效果仍然是从网络来抓取DTD来验证
                            }
                     }
                 );
            Document document = builder.parse(file);

**Comment by javamxd** [comment]
这个在0.1版本中已经改成xsd验证了。不过还是会有这种错误。
计划下个版本去掉从网络上获取xsd验证。
