### ISSUE TITLE
sql查询后一直占用数据库连接池不会释放，请问是什么原因

### ISSUE THREAD

**Issue by 15757395583** [ssssssss-team/magic-api#20]
是需要修改配置嘛？现在通常方案是直接重启服务就能释放，比较麻烦，想问问有没有代码上可以解决的方案

**Comment by 15757395583** [comment]
使用的是oracle数据库

**Comment by javamxd** [comment]
你用的什么版本，之前有的版本是修改数据源后是不会释放连接，除此之外还没发现。是不是你连接池配置有问题。

**Comment by 15757395583** [comment]
现在用的1.1.0版本，是不是用的版本比较低？如果过低的话怎么升级比较好




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月2日(星期五) 下午3:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ssssssss-team/magic-api] sql查询后一直占用数据库连接池不会释放，请问是什么原因 (#20)





 
你用的什么版本，之前有的版本是修改数据源后是不会释放连接，除此之外还没发现。是不是你连接池配置有问题。

**Comment by javamxd** [comment]
你用的什么版本，之前有的版本是修改数据源后是不会释放连接，除此之外还没发现。是不是你连接池配置有问题。

**Comment by javamxd** [comment]
升到最新版就行了
