### ISSUE TITLE
请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因

### ISSUE THREAD

**Issue by 15757395583** [ssssssss-team/magic-api#23]
写了一段脚本
if(data.id==null){
}
提示错误org.ssssssss.script.exception.MagicScriptException java.lang.string中找不到属性id或者方法getId,
请问是什么原因导致的，现在magic-script版本是1.4.5

**Comment by javamxd** [comment]
这个写法好像是有BUG。你可以改用 if(data?.id)
另外这个错误似乎data是String类型的？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 晚上7:17
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)





 
写了一段脚本
 if(data.id==null){
 }
 提示错误org.ssssssss.script.exception.MagicScriptException java.lang.string中找不到属性id或者方法getId,
 请问是什么原因导致的，现在magic-script版本是1.4.5

**Comment by 15757395583** [comment]
data是一个对象，刚刚试了下if(data?.id)的写法，也还是同样的错误。之前1.0版本好像写的没问题，最近升级1.3就出现这个情况。

有没有其他写法，比如像JavaScript那样，把数据转换成对象再.id?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 晚上7:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)





 这个写法好像是有BUG。你可以改用 if(data?.id) 
 另外这个错误似乎data是String类型的？ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年7月14日(星期三) 晚上7:17 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23) 
 
 
 
 
 
   
 写了一段脚本 
  if(data.id==null){ 
  } 
  提示错误org.ssssssss.script.exception.MagicScriptException java.lang.string中找不到属性id或者方法getId, 
  请问是什么原因导致的，现在magic-script版本是1.4.5

**Comment by javamxd** [comment]
你这应该就是字符串了。
看起来应该还是JSON字符串吧？
转JSON对象可以 data::json


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 晚上7:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)





 data是一个对象，刚刚试了下if(data?.id)的写法，也还是同样的错误。之前1.0版本好像写的没问题，最近升级1.3就出现这个情况。 
 
 有没有其他写法，比如像JavaScript那样，把数据转换成对象再.id? 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年7月14日(星期三) 晚上7:18 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23) 
 
 
 
 
 
  这个写法好像是有BUG。你可以改用 if(data?.id)  
  另外这个错误似乎data是String类型的？  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年7月14日(星期三) 晚上7:17  
  ***@***.***&amp;amp;gt;;  
  ***@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;[ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)  
   
   
   
   
   
     
  写了一段脚本  
   if(data.id==null){  
   }  
   提示错误org.ssssssss.script.exception.MagicScriptException java.lang.string中找不到属性id或者方法getId,  
   请问是什么原因导致的，现在magic-script版本是1.4.5

**Comment by 15757395583** [comment]
额，现在转换json就出现问题了，提示不支持类型,java.util.LinkedHashMap
var dat = data::json;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 晚上7:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)





 你这应该就是字符串了。 
 看起来应该还是JSON字符串吧？ 
 转JSON对象可以 data::json 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年7月14日(星期三) 晚上7:22 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23) 
 
 
 
 
 
  data是一个对象，刚刚试了下if(data?.id)的写法，也还是同样的错误。之前1.0版本好像写的没问题，最近升级1.3就出现这个情况。  
   
  有没有其他写法，比如像JavaScript那样，把数据转换成对象再.id?  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年7月14日(星期三) 晚上7:18  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)  
   
   
   
   
   
   这个写法好像是有BUG。你可以改用 if(data?.id)   
   另外这个错误似乎data是String类型的？   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2021年7月14日(星期三) 晚上7:17   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;[ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)   
     
     
     
     
     
       
   写了一段脚本   
    if(data.id==null){   
    }   
    提示错误org.ssssssss.script.exception.MagicScriptException java.lang.string中找不到属性id或者方法getId,   
    请问是什么原因导致的，现在magic-script版本是1.4.5

**Comment by javamxd** [comment]
...那你这个就不是String了，data?.id 应该是没有问题的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 晚上7:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)





 额，现在转换json就出现问题了，提示不支持类型,java.util.LinkedHashMap 
 var dat = data::json; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年7月14日(星期三) 晚上7:24 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23) 
 
 
 
 
 
  你这应该就是字符串了。  
  看起来应该还是JSON字符串吧？  
  转JSON对象可以 data::json  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年7月14日(星期三) 晚上7:22  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)  
   
   
   
   
   
   data是一个对象，刚刚试了下if(data?.id)的写法，也还是同样的错误。之前1.0版本好像写的没问题，最近升级1.3就出现这个情况。   
     
   有没有其他写法，比如像JavaScript那样，把数据转换成对象再.id?   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2021年7月14日(星期三) 晚上7:18   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)   
     
     
     
     
     
    这个写法好像是有BUG。你可以改用 if(data?.id)    
    另外这个错误似乎data是String类型的？    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2021年7月14日(星期三) 晚上7:17    
    ***@***.***&amp;amp;amp;amp;gt;;    
    ***@***.***&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;[ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)    
       
       
       
       
       
         
    写了一段脚本    
     if(data.id==null){    
     }    
     提示错误org.ssssssss.script.exception.MagicScriptException java.lang.string中找不到属性id或者方法getId,    
     请问是什么原因导致的，现在magic-script版本是1.4.5

**Comment by 15757395583** [comment]
打断点研究了下数据类型，发现是接收数据有问题影响脚本执行了。
现在可以，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 晚上7:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)





 ...那你这个就不是String了，data?.id 应该是没有问题的。 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年7月14日(星期三) 晚上7:30 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23) 
 
 
 
 
 
  额，现在转换json就出现问题了，提示不支持类型,java.util.LinkedHashMap  
  var dat = data::json;  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年7月14日(星期三) 晚上7:24  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)  
   
   
   
   
   
   你这应该就是字符串了。   
   看起来应该还是JSON字符串吧？   
   转JSON对象可以 data::json   
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2021年7月14日(星期三) 晚上7:22   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)   
     
     
     
     
     
    data是一个对象，刚刚试了下if(data?.id)的写法，也还是同样的错误。之前1.0版本好像写的没问题，最近升级1.3就出现这个情况。    
       
    有没有其他写法，比如像JavaScript那样，把数据转换成对象再.id?    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2021年7月14日(星期三) 晚上7:18    
    ***@***.***&amp;amp;amp;amp;gt;;    
    ***@***.******@***.***&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)    
       
       
       
       
       
     这个写法好像是有BUG。你可以改用 if(data?.id)     
     另外这个错误似乎data是String类型的？     
         
         
         
         
     ------------------&amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;nbsp;------------------     
     发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;amp;amp;amp;amp;gt;;     
     发送时间:&amp;amp;amp;amp;amp;nbsp;2021年7月14日(星期三) 晚上7:17     
     ***@***.***&amp;amp;amp;amp;amp;gt;;     
     ***@***.***&amp;amp;amp;amp;amp;gt;;     
     主题:&amp;amp;amp;amp;amp;nbsp;[ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)     
         
         
         
         
         
           
     写了一段脚本     
      if(data.id==null){     
      }     
      提示错误org.ssssssss.script.exception.MagicScriptException java.lang.string中找不到属性id或者方法getId,     
      请问是什么原因导致的，现在magic-script版本是1.4.5

**Comment by javamxd** [comment]
能否告知一下具体原因？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 晚上7:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)





 打断点研究了下数据类型，发现是接收数据有问题影响脚本执行了。 
 现在可以，谢谢！ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年7月14日(星期三) 晚上7:32 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23) 
 
 
 
 
 
  ...那你这个就不是String了，data?.id 应该是没有问题的。  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年7月14日(星期三) 晚上7:30  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)  
   
   
   
   
   
   额，现在转换json就出现问题了，提示不支持类型,java.util.LinkedHashMap   
   var dat = data::json;   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2021年7月14日(星期三) 晚上7:24   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)   
     
     
     
     
     
    你这应该就是字符串了。    
    看起来应该还是JSON字符串吧？    
    转JSON对象可以 data::json    
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2021年7月14日(星期三) 晚上7:22    
    ***@***.***&amp;amp;amp;amp;gt;;    
    ***@***.******@***.***&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)    
       
       
       
       
       
     data是一个对象，刚刚试了下if(data?.id)的写法，也还是同样的错误。之前1.0版本好像写的没问题，最近升级1.3就出现这个情况。     
         
     有没有其他写法，比如像JavaScript那样，把数据转换成对象再.id?     
         
         
         
         
     ------------------&amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;nbsp;------------------     
     发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;amp;amp;amp;amp;gt;;     
     发送时间:&amp;amp;amp;amp;amp;nbsp;2021年7月14日(星期三) 晚上7:18     
     ***@***.***&amp;amp;amp;amp;amp;gt;;     
     ***@***.******@***.***&amp;amp;amp;amp;amp;gt;;     
     主题:&amp;amp;amp;amp;amp;nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)     
         
         
         
         
         
      这个写法好像是有BUG。你可以改用 if(data?.id)      
      另外这个错误似乎data是String类型的？      
           
           
           
           
      ------------------&amp;amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;amp;nbsp;------------------      
      发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;amp;amp;amp;amp;amp;gt;;      
      发送时间:&amp;amp;amp;amp;amp;amp;nbsp;2021年7月14日(星期三) 晚上7:17      
      ***@***.***&amp;amp;amp;amp;amp;amp;gt;;      
      ***@***.***&amp;amp;amp;amp;amp;amp;gt;;      
      主题:&amp;amp;amp;amp;amp;amp;nbsp;[ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)      
           
           
           
           
           
             
      写了一段脚本      
       if(data.id==null){      
       }      
       提示错误org.ssssssss.script.exception.MagicScriptException java.lang.string中找不到属性id或者方法getId,      
       请问是什么原因导致的，现在magic-script版本是1.4.5

**Comment by 15757395583** [comment]
传参数据类型不对导致的，
原本接收的data应该是个json数组，但是因为默认测试数据填充的是个json对象，
导致在遍历for(dat in data)后，
得到的dat被脚本判断为字符串了，所以.id出现问题了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 晚上7:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)





 能否告知一下具体原因？ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年7月14日(星期三) 晚上7:49 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23) 
 
 
 
 
 
  打断点研究了下数据类型，发现是接收数据有问题影响脚本执行了。  
  现在可以，谢谢！  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2021年7月14日(星期三) 晚上7:32  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)  
   
   
   
   
   
   ...那你这个就不是String了，data?.id 应该是没有问题的。   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2021年7月14日(星期三) 晚上7:30   
   ***@***.***&amp;amp;amp;gt;;   
   ***@***.******@***.***&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)   
     
     
     
     
     
    额，现在转换json就出现问题了，提示不支持类型,java.util.LinkedHashMap    
    var dat = data::json;    
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2021年7月14日(星期三) 晚上7:24    
    ***@***.***&amp;amp;amp;amp;gt;;    
    ***@***.******@***.***&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)    
       
       
       
       
       
     你这应该就是字符串了。     
     看起来应该还是JSON字符串吧？     
     转JSON对象可以 data::json     
         
         
     ------------------&amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;nbsp;------------------     
     发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;amp;amp;amp;amp;gt;;     
     发送时间:&amp;amp;amp;amp;amp;nbsp;2021年7月14日(星期三) 晚上7:22     
     ***@***.***&amp;amp;amp;amp;amp;gt;;     
     ***@***.******@***.***&amp;amp;amp;amp;amp;gt;;     
     主题:&amp;amp;amp;amp;amp;nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)     
         
         
         
         
         
      data是一个对象，刚刚试了下if(data?.id)的写法，也还是同样的错误。之前1.0版本好像写的没问题，最近升级1.3就出现这个情况。      
           
      有没有其他写法，比如像JavaScript那样，把数据转换成对象再.id?      
           
           
           
           
      ------------------&amp;amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;amp;nbsp;------------------      
      发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;amp;amp;amp;amp;amp;gt;;      
      发送时间:&amp;amp;amp;amp;amp;amp;nbsp;2021年7月14日(星期三) 晚上7:18      
      ***@***.***&amp;amp;amp;amp;amp;amp;gt;;      
      ***@***.******@***.***&amp;amp;amp;amp;amp;amp;gt;;      
      主题:&amp;amp;amp;amp;amp;amp;nbsp;Re: [ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)      
           
           
           
           
           
       这个写法好像是有BUG。你可以改用 if(data?.id)       
       另外这个错误似乎data是String类型的？       
             
             
             
             
       ------------------&amp;amp;amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;amp;amp;nbsp;------------------       
       发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&amp;amp;amp;amp;amp;amp;amp;gt;;       
       发送时间:&amp;amp;amp;amp;amp;amp;amp;nbsp;2021年7月14日(星期三) 晚上7:17       
       ***@***.***&amp;amp;amp;amp;amp;amp;amp;gt;;       
       ***@***.***&amp;amp;amp;amp;amp;amp;amp;gt;;       
       主题:&amp;amp;amp;amp;amp;amp;amp;nbsp;[ssssssss-team/magic-api] 请问提示”执行脚本出错“ 这种错误是什么原因导致的。查了半天没找到原因 (#23)       
             
             
             
             
             
               
       写了一段脚本       
        if(data.id==null){       
        }       
        提示错误org.ssssssss.script.exception.MagicScriptException java.lang.string中找不到属性id或者方法getId,       
        请问是什么原因导致的，现在magic-script版本是1.4.5
