### ISSUE TITLE
按官方文档调用http模块，提示.post()有问题，且连接超时

### ISSUE THREAD

**Issue by 15757395583** [ssssssss-team/magic-api#24]
import http;
return http.connect('接口地址').post().getBody()；

内网环境，接口在postman上已经调通肯定能访问，但是按文档写http请求就都连接失败，是哪里拦截了需要配置嘛？

**Comment by javamxd** [comment]
http模块是用RestTemplate封装的，本身没做什么处理。要么网络环境有问题，要么注入进来的RestTemplate有问题，检查一下。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月22日(星期四) 下午5:23
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ssssssss-team/magic-api] 按官方文档调用http模块，提示.post()有问题，且连接超时 (#24)
