### ISSUE TITLE
如何切换自定义的db？

### ISSUE THREAD

**Issue by just3019** [ssssssss-team/magic-api#26]
我想要使用我的localhost这个数据库进行查询操作，如何切换sql。

我下面的截图是使用默认数据库进行查询的。

![image](https://user-images.githubusercontent.com/5235712/129999604-e0d1d153-def2-426e-938a-7e354661a513.png)

![image](https://user-images.githubusercontent.com/5235712/129999696-547e5c08-a846-42b5-8ac9-4059920dc51e.png)

**Comment by javamxd** [comment]
第三行，`db.select(sql)` 换成 `db.localhost.select(sql)`

**Comment by just3019** [comment]
THKS
