### ISSUE TITLE
pg数据库查询返回字段全部为小写

### ISSUE THREAD

**Issue by 15757395583** [ssssssss-team/magic-api#33]
比如数据库查询 userPhone 字段，实际返回userphone，这个问题应该怎么解决

**Comment by javamxd** [comment]
`db.camel().select()`

**Comment by 15757395583** [comment]
是这样写的，sql里也有定义别名，但是返回都转成小写了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月21日(星期天) 中午12:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ssssssss-team/magic-api] pg数据库查询返回字段全部为小写 (Issue #33)





 
db.camel().select()
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 15757395583** [comment]
是这样写的，sql里也有定义别名，但是返回都转成小写了


--10:13更新
原因找到了，不是magic项目问题，是pg数据库定义的别名不生效的问题。
不好意思。


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月21日(星期天) 中午12:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ssssssss-team/magic-api] pg数据库查询返回字段全部为小写 (Issue #33)





 
db.camel().select()
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
