### ISSUE TITLE
java怎么访问db模块

### ISSUE THREAD

**Issue by ayhome** [ssssssss-team/magic-api#35]
如题  一些java方法要单独处理,是否可以直接调用 magic 的模块?

**Comment by javamxd** [comment]
db模块比较特殊，有些参数是由脚本引擎传入的，所以不能直接调用。

**Comment by ayhome** [comment]
哦  多谢, 那么如果在JAVA中实现查询数据库, 还是的自己实现java bean  对吧.

**Comment by javamxd** [comment]
是的

**Comment by ayhome** [comment]
那么  java 能不能访问 magic 的方法呢, magic 写的自定义的function

**Comment by javamxd** [comment]
> 那么 java 能不能访问 magic 的方法呢, magic 写的自定义的function

这个不就是普通的bean么。。注入进来就能用了
