### ISSUE TITLE
反馈一个问题,关于插入数据 字段默认为空的

### ISSUE THREAD

**Issue by ayhome** [ssssssss-team/magic-api#36]
我是才从PHP转过来的, 遇见一个很奇怪的问题   
数据库 mysql 5.7.x   
使用插入遇见   
` return db.insert("insert into db_dept(name,code) values('ad222min','admin')");`   
提示   
`org.ssssssss.script.exception.MagicScriptException: PreparedStatementCallback; Field 'remark' doesn't have a default value; nested exception is java.sql.SQLException: Field 'remark' doesn't have a default value at Row:53~53,Col:11~74`    
 但是我直接数据库里面执行  
`insert into db_dept(name,code) values('ad222min','admin')`   
是正常的,   
mysql.ini 已经设置  
`sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"`    
通用的 单表操作 插入数据也一样的问题,   
我也找不到原因了,     
但是 如果代入  remark 随便一个字符串,就成功了

**Comment by javamxd** [comment]
`remark`这列不能为空，又没有默认值，插入不就这样报错了吗？这不是很正常吗。。

**Comment by ayhome** [comment]
当我的遇见 不代入 remark 的时候, 数据库会默认为空,  并且把这个SQL遇见直接在MYSQL运行时正常的,     
单表查询的时候 把remark  = ''   也会同样的错误
