### ISSUE TITLE
前端无法展示接口运行日志

### ISSUE THREAD

**Issue by li751961845** [ssssssss-team/magic-api#37]
bus.$on('ws_log', rows => {
    this.onLogReceived(rows[0])})
    这个ws_log是指什么呢 rows没有数据啊

**Comment by javamxd** [comment]
检查`websocket`是不是连上了，后台是不是用了`devtools`了，用了的话去掉就行

**Comment by li751961845** [comment]
websocket的连接需要调nginx嘛，本地起项目但调用接口是dev环境的ws://localhost:8000/api/magic-api/magic/web/console拼接后一直连接不上WebSocket is closed before the connection is established.

**Comment by javamxd** [comment]
经过nginx的话，要配置nginx的，让其支持websocket。

**Comment by li751961845** [comment]
感谢，我再调试一下吧
