### ISSUE TITLE
返回json 数据 时 数值类型时long 长整型的值时会识别成int 而无法正确返回

### ISSUE THREAD

**Issue by dcdlove** [ssssssss-team/magic-api#38]
![image](https://user-images.githubusercontent.com/10043691/150056130-61ccc6a7-3543-4b37-bbe5-67f288117230.png)

**Comment by javamxd** [comment]
这个没啥事的。纯粹是编辑器的问题。。

**Comment by dcdlove** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by dcdlove** [comment]
知道了，多谢
