### ISSUE TITLE
sql注入攻击？

### ISSUE THREAD

**Issue by lincoln310** [ssssssss-team/magic-api#39]
请问，能防止sql注入攻击吗？

**Comment by javamxd** [comment]
只要sql中使用#{}的参数都不会有注入风险，使用${}的或者拼接字符串的才有可能注入。具体的要看你自己。

**Comment by lincoln310** [comment]
防止sql注入攻击，就是要防止各类方式啊。#{}称之为合法规则，但是需要防止违法使用啊。

javamxd ***@***.***> 于2022年1月23日周日 11:53写道：
