### ISSUE TITLE
oracle trunc sysdate 时间错乱

### ISSUE THREAD

**Issue by changzhichen** [ssssssss-team/magic-api#42]
查询oracle数据库时间错误

环境：
1.oracle版本11g
2.magic-api 版本
<img width="695" alt="image" src="https://user-images.githubusercontent.com/27051861/155099218-368333ed-fdf3-48a5-8943-1daa31085cfb.png">

查询结果：
![image](https://user-images.githubusercontent.com/27051861/155099515-dab86a28-08cf-4a03-889d-ab535bc8f732.png)

期望：
trunc函数可正常使用

**Comment by javamxd** [comment]
这个是JSON序列化的问题。https://www.ssssssss.org/magic-api/guide/faq.html#%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AEjson%E6%97%A5%E6%9C%9F%E7%9A%84%E6%A0%BC%E5%BC%8F




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月22日(星期二) 下午5:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ssssssss-team/magic-api] oracle trunc sysdate 时间错乱 (Issue #42)





 
查询oracle数据库时间错误
 
环境：
 1.oracle版本11g
 2.magic-api 版本
 
 
查询结果：
 
 
期望：
 trunc函数可正常使用
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by changzhichen** [comment]
嗯，解决了
