### ISSUE TITLE
undefined is not an object (evaluating 'f.forEach')

### ISSUE THREAD

**Issue by sj-dev** [ssssssss-team/magic-api#47]
后台无错误，前台访问的时候报
undefined is not an object (evaluating 'f.forEach')
undefined is not an object (evaluating 'B.length')

<img width="525" alt="image" src="https://user-images.githubusercontent.com/10184494/160740310-564a8ac4-7398-42d7-906d-abd83f26e35f.png">

**Comment by javamxd** [comment]
升级版本试试
