### ISSUE TITLE
ORDER BY顺序问题

### ISSUE THREAD

**Issue by 2mi** [ssssssss-team/magic-api#54]
https://github.com/ssssssss-team/magic-api/blob/25fa9d08396314f4735dd7f7ca3a1a4f806def36/magic-api/src/main/java/org/ssssssss/magicapi/modules/db/table/NamedTable.java#L487

ORDER BY和GROUP BY的顺序不是有点问题吗

**Comment by javamxd** [comment]
是的，下个版本修复
