### ISSUE TITLE
生产环境，运行一段时间后，再次访问magic的接口时，报404

### ISSUE THREAD

**Issue by changzhichen** [ssssssss-team/magic-api#59]
maven依赖
<img width="599" alt="image" src="https://user-images.githubusercontent.com/27051861/179909262-aff503ff-d4a0-47dc-9d7f-d688d10f5ee5.png">

环境：springboot + magic集成
linux正常运行一段时间后，再次访问magic中的接口时，报错404，重新启动后正常

报错截图如下：
![image](https://user-images.githubusercontent.com/27051861/179909637-249d42b2-6ad6-4d81-96a7-2af6dcf166b7.png)

期望：能正常调用接口

**Comment by javamxd** [comment]
升级至1.7.5试试






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月20日(星期三) 下午2:14
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ssssssss-team/magic-api] 生产环境，运行一段时间后，再次访问magic的接口时，报404 (Issue #59)





 
maven依赖
 
 
环境：springboot + magic集成
 linux正常运行一段时间后，再次访问magic中的接口时，报错404，重新启动后正常
 
报错截图如下：
 
 
期望：能正常调用接口
