### ISSUE TITLE
mybatis中的foreach语句如何支持？

### ISSUE THREAD

**Issue by skynice** [ssssssss-team/magic-api#6]
mybatis中的foreach语句怎么编写？

**Comment by javamxd** [comment]
v0.2.0之前的版本是支持的，用法和myabtis的foreach是一样的。
不过0.2.0版本开始，移除了XML的方式。
现在，如果内容是集合，会自动展开。比如写了 where id in (#{ids}) 会自动变成 where id in (?,?,?,?)

**Comment by javamxd** [comment]
未来可能还会把XML的方式移植回来。

**Comment by skynice** [comment]
测试了，很好用，建议在文档里补充这部分描述

**Comment by javamxd** [comment]
> 测试了，很好用，建议在文档里补充这部分描述

收到
