### ISSUE TITLE
建议：接口拦截器中ApiInfo中的path能否返回完整path

### ISSUE THREAD

**Issue by xinwu-yang** [ssssssss-team/magic-api#63]
magic-api 版本：2.0.2

我在接口平台配置的path是/map/point/search

但是拦截器中我通过ApiInfo只能拿到 search，但是我其实想拿到整个path

![image](https://user-images.githubusercontent.com/12267648/195481805-55cce342-9c12-4ff7-b472-9a7be2fb635c.png)

**Comment by javamxd** [comment]
magicResourceService.getGroupPath(info.getGroupId()) 获取分组路径在拼接即可




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月13日(星期四) 上午10:05
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ssssssss-team/magic-api] 建议：接口拦截器中ApiInfo中的path能否返回完整path (Issue #63)





 
我在接口平台配置的path是/map/point/search
 
但是拦截器中我通过ApiInfo只能拿到 search，但是我其实想拿到整个path

**Comment by xinwu-yang** [comment]
转提交到 gitee
