### ISSUE TITLE
BUG，执行器会把转移字符去掉

### ISSUE THREAD

**Issue by wo8335224** [ssssssss-team/magic-api#68]
脚本代码：
![image](https://user-images.githubusercontent.com/10435131/210177469-91efce30-2986-413b-973f-1ac8eee9aeb0.png)
```

var encode = payload => {
   return toJson(payload)
}
return encode('{"messageType":"FUNCTIONS","function":"setClock","data":{"deviceId":"9617529963","clock":"[{\"time\":\"05:00\",\"repeat\":\"1111111\",\"enabled\":true}]"}}')

```

执行报错

![image](https://user-images.githubusercontent.com/10435131/210177339-34f1fdeb-7248-40aa-9003-3e5ba4d4dccf.png)

封装的自定义函数

![image](https://user-images.githubusercontent.com/10435131/210177328-85d934c7-558d-463d-9768-287e6c40f069.png)

断点复现：

![image](https://user-images.githubusercontent.com/10435131/210177529-a3652fa3-caa2-4fe0-b080-97574277e780.png)

转义字符没了，就不是一个标准JSON，导致出错。求指导。版本<magic-script.version>1.8.6</magic-script.version>

**Comment by javamxd** [comment]
"clock":"[{\\\"time\\\":\\\"05:00\\\",\\\"repeat\\\":\\\"1111111\\\",\\\"enabled\\\":true}]"




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月2日(星期一) 凌晨0:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [ssssssss-team/magic-api] BUG，执行器会把转移字符去掉 (Issue #68)





 
脚本代码：
 
  var encode = payload =&gt; {    return toJson(payload) } return encode('{"messageType":"FUNCTIONS","function":"setClock","data":{"deviceId":"9617529963","clock":"[{\"time\":\"05:00\",\"repeat\":\"1111111\",\"enabled\":true}]"}}')  
执行报错
 

 
封装的自定义函数
 

 
断点复现：
 

 
转义字符没了，就不是一个标准JSON，导致出错。求指导。版本<magic-script.version&gt;1.8.6</magic-script.version&gt;

**Comment by wo8335224** [comment]
谢谢，已可以。

可以方便再说下，哪几个类是处理这个转义的事情的？

**Comment by javamxd** [comment]
org.ssssssss.script.parsing.ast.literal.StringLiteral




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月3日(星期二) 下午4:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ssssssss-team/magic-api] BUG，执行器会把转移字符去掉 (Issue #68)





 
谢谢，已可以。
 
可以方便再说下，哪几个类是处理这个转义的事情的？
