### ISSUE TITLE
sql <trim> 标签

### ISSUE THREAD

**Issue by chgang** [ssssssss-team/magic-api#7]
有类似mybatis<trim>标签吗？要去除末尾逗号之类的问题

**Comment by javamxd** [comment]
没有。

**Comment by chgang** [comment]
现在前端body入参为整形，后端获取的是带小数点的，请求方式 application/json

**Comment by javamxd** [comment]
是int啊，能提供一下入参吗。

**Comment by chgang** [comment]
params":{
            "isDetail": "1",} 比如这个前端如果传 1 ， 后端获取的是1.0

**Comment by javamxd** [comment]
这不是字符串吗

**Comment by chgang** [comment]
params":{
"isDetail": 1}
